[build]
  base    = "apps/web"
  command = "npm install && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/admin"
  to     = "/admin/index.html"
  status = 200
  force  = true

[[redirects]]
  from   = "/admin/*"
  to     = "/admin/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
